openapi: 3.0.0
info:
  description: This is a simple API in order to bridge the use of grit-db to grit-ui.
  version: 1.0.0
  title: grit-api
  # put the contact info for your development or API team
  contact:
    email: dp24@sanger.ac.uk
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080/api/v2

tags:
- name: utilities

paths:
  /curatedtol:
    get:
      tags:
        - utilities
      summary: returns a list of TolIDs which have passed through GRIT.
      produces:
        - application/json
      parameters:
        - in: query
          name: project
          type: string
          enum: [VGP+, VGP_orders, 25_genomes, Darwin, Other]
          description: Filter the list of TolIDs by the project they are associated with.
        - in: query
          name: slclade
          type: string
          enum: [a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z]
          description: Filter the list of TolIDs by the single letter clade identifier
        - in: query
          name: dlclade
          type: string
          description: Filter the list of TolIDs by the double letter clade identifier
        - in: query
          name: fullclade
          type: string
          # enum could be added in the future, but clade are still being expanded
          description: Filter list by full name of clade (enum to be added)
      responses:
        "200":
          description: Valid Call - OK
        "400":
          description: Valid Call - No TolID in db
        "404":
          description: Invalid Call

  /projects/{id}:
    get:
      tags:
        - utilities
      summary: returns a list of all samples associated with project/{id}
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: string
          enum: [VGP+, VGP_orders, 25_genomes, Darwin, Other]
          description: The project name.
      responses:
        "200":
          description: Valid Call - OK
        "400":
          description: Valid Call - No project in db
        "404":
          description: Invalid Call

  /date:
    get:
      tags:
        - utilities
      parameters:
        - name: start_date
          in: query
          type: string
          format: date
          description: The start date for data pulled from the database in format `yyyy-mm-dd`
          default: 2019-01-09
        - name: end_date
          in: query
          type: string
          format: date
          description: The end date for the data pulled from the database in format `yyyy-mm-dd`
      responses:
        "200":
          description: Valid Call - OK
        "404":
          description: Invalid Call - Dates maybe wrong or incomplete
